### ISSUE TITLE
Demo video projects 

### ISSUE THREAD

**Issue by rwaldron** [brianchirls/popcorn-base#2]
In the demo video shown here:

http://brianchirls.github.com/popcorn-base/examples/

There are several Popcorn projects shown that are actually not using "Popcorn Base" -- this is a bit misleading.

**Comment by brianchirls** [comment]
Rick,

The examples only use plugins in this repo, and all of the plugins are built upon Popcorn Base. If you're talking about the pieces actually _in_ the recorded video, then yes you're right. I'm just using Brett's video that he made for mozillapopcorn.org - didn't have time to make my own.

Is this what you mean?

**Comment by rwaldron** [comment]
Yes, that's what I meant, the video inside the video, sorry for being unclear. Since you didn't actually make it, it's unreasonable to ask you to change it, so I'm closing this ticket. Sorry for the noise.

**Comment by brianchirls** [comment]
Cool. If you have any other suggestions of hosted videos out there to use for the smaller examples, please feel free to share.
